# Generated by Django 3.2.6 on 2021-08-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='unique_id',
        ),
    ]
