# Generated by Django 3.2.5 on 2021-07-31 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 7, 31, 13, 42, 52, 37793)),
        ),
        migrations.AlterField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='quizapi.question'),
        ),
    ]
