# Generated by Django 3.2.6 on 2021-08-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstatistic',
            name='user_name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='quizstatistic',
            name='user_surname',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='useranswers',
            name='date_of_completion',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
