# Generated by Django 3.2.6 on 2021-08-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0002_auto_20210819_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='date_of_completion',
        ),
        migrations.AddField(
            model_name='quizstatistic',
            name='date_of_completion',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
