version: "3"

services: 
  django-server:
    build: ./backend
    command: python backend/server/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/backend
    ports: 
      - "8000:8000"
  client: 
    build: ./frontend
