# Generated by Django 3.2.5 on 2021-07-20 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztesting',
            name='brand',
            field=models.CharField(max_length=64, verbose_name='Брэнд'),
        ),
        migrations.AlterField(
            model_name='quiztesting',
            name='car_type',
            field=models.IntegerField(choices=[(1, 'Купе'), (2, 'Кросовер'), (3, 'Универсал'), (4, 'Внедородник')], verbose_name='Тип машины'),
        ),
        migrations.AlterField(
            model_name='quiztesting',
            name='color',
            field=models.CharField(max_length=64, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='quiztesting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='quiztesting',
            name='vin',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Вин'),
        ),
    ]
