# Generated by Django 3.2.5 on 2021-07-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210720_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztesting',
            name='user',
            field=models.CharField(max_length=65, verbose_name='Пользователь'),
        ),
    ]
