# Generated by Django 3.2.5 on 2021-07-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiztesting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(db_index=True, max_length=25, verbose_name='Email')),
                ('user_name', models.CharField(max_length=25, verbose_name='User name')),
                ('user_password', models.TextField(verbose_name='Password')),
            ],
        ),
        migrations.RenameModel(
            old_name='QuizTesting',
            new_name='Quiz',
        ),
    ]
